services:
  db:
    image: postgres:16
    container_name: tasks_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: tasks_api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      PORT: 3000
      HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: tasks_db

volumes:
  pgdata:
